// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace BuildIt.CognitiveServices
{

    /// <summary>
    /// </summary>
    public partial interface IEntityLinkingAPI : System.IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        System.Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        Newtonsoft.Json.JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        Newtonsoft.Json.JsonSerializerSettings DeserializationSettings { get; }


        /// <summary>
        /// Entity Linking is a natural language processing tool to help
        /// analyzing text for your application. Entity Linking recognize a
        /// named-entity from given text and  aligning a textual mention of
        /// the entity to an appropriate entry in a knowledge base.
        /// </summary>
        /// <param name="requestBody">
        /// Input content
        /// </param>
        /// <param name='selection'>
        /// The specific word or phrase within the text that is to be entity
        /// linked. If not specified, the service will try to recognize and
        /// identify all the entities within the input text.
        /// </param>
        /// <param name='offset'>
        /// The location (in offset by characters) of the selected word or
        /// phrase within the input text. Used to distinguish when there are
        /// multiple instances of the same words or phrases within the input
        /// text. Only valid when the selection is specified.
        /// </param>
        /// <param name='subscriptionKey'>
        /// subscription key in url
        /// </param>
        /// <param name='ocpApimSubscriptionKey'>
        /// subscription key in header
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse> LinkEntityWithHttpMessagesAsync(string requestBody, string selection = default(string), string offset = default(string), string subscriptionKey = default(string), string ocpApimSubscriptionKey = default(string), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

    }
}
