// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace BuildIt.CognitiveServices.Models
{
    using System.Linq;

    public partial class BatchJobInfo
    {
        /// <summary>
        /// Initializes a new instance of the BatchJobInfo class.
        /// </summary>
        public BatchJobInfo() { }

        /// <summary>
        /// Initializes a new instance of the BatchJobInfo class.
        /// </summary>
        /// <param name="id">Unique batch identifier</param>
        /// <param name="requestinfo">Description of the batch request</param>
        /// <param name="status">Status of the batch job (it is actually the
        /// job status: Registered, Ready, InProgress, Canceling, Canceled,
        /// Succeeded, Failed)</param>
        public BatchJobInfo(string id = default(string), BatchJobsRequestInfo requestinfo = default(BatchJobsRequestInfo), string status = default(string))
        {
            Id = id;
            Requestinfo = requestinfo;
            Status = status;
        }

        /// <summary>
        /// Gets or sets unique batch identifier
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets description of the batch request
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "requestinfo")]
        public BatchJobsRequestInfo Requestinfo { get; set; }

        /// <summary>
        /// Gets or sets status of the batch job (it is actually the job
        /// status: Registered, Ready, InProgress, Canceling, Canceled,
        /// Succeeded, Failed)
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "status")]
        public string Status { get; set; }

    }
}
