// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace BuildIt.CognitiveServices.Models
{
    using System.Linq;

    public partial class DetectedLanguageV2
    {
        /// <summary>
        /// Initializes a new instance of the DetectedLanguageV2 class.
        /// </summary>
        public DetectedLanguageV2() { }

        /// <summary>
        /// Initializes a new instance of the DetectedLanguageV2 class.
        /// </summary>
        /// <param name="name">Long name of a detected language (e.g. English,
        /// French).</param>
        /// <param name="iso6391Name">A two letter representation of the
        /// detected language according to the ISO 639-1 standard (e.g. en,
        /// fr).</param>
        /// <param name="score">A confidence score between 0 and 1. Scores
        /// close to 1 indicate 100% certainty that the identified language
        /// is true.</param>
        public DetectedLanguageV2(string name = default(string), string iso6391Name = default(string), double? score = default(double?))
        {
            Name = name;
            Iso6391Name = iso6391Name;
            Score = score;
        }

        /// <summary>
        /// Gets or sets long name of a detected language (e.g. English,
        /// French).
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets a two letter representation of the detected language
        /// according to the ISO 639-1 standard (e.g. en, fr).
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "iso6391Name")]
        public string Iso6391Name { get; set; }

        /// <summary>
        /// Gets or sets a confidence score between 0 and 1. Scores close to 1
        /// indicate 100% certainty that the identified language is true.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "score")]
        public double? Score { get; set; }

    }
}
