// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace BuildIt.CognitiveServices.Models
{
    using System.Linq;

    public partial class ErrorStats
    {
        /// <summary>
        /// Initializes a new instance of the ErrorStats class.
        /// </summary>
        public ErrorStats() { }

        /// <summary>
        /// Initializes a new instance of the ErrorStats class.
        /// </summary>
        /// <param name="errorCode">Error code for error catalog lines</param>
        /// <param name="errorCodeCount">Count of catalog lines with specified
        /// error code</param>
        public ErrorStats(string errorCode = default(string), int? errorCodeCount = default(int?))
        {
            ErrorCode = errorCode;
            ErrorCodeCount = errorCodeCount;
        }

        /// <summary>
        /// Gets or sets error code for error catalog lines
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "errorCode")]
        public string ErrorCode { get; set; }

        /// <summary>
        /// Gets or sets count of catalog lines with specified error code
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "errorCodeCount")]
        public int? ErrorCodeCount { get; set; }

    }
}
