// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace BuildIt.CognitiveServices.Models
{
    using System.Linq;

    public partial class ModelUsageStatisticsResponse
    {
        /// <summary>
        /// Initializes a new instance of the ModelUsageStatisticsResponse
        /// class.
        /// </summary>
        public ModelUsageStatisticsResponse() { }

        /// <summary>
        /// Initializes a new instance of the ModelUsageStatisticsResponse
        /// class.
        /// </summary>
        /// <param name="interval">The input interval for this response</param>
        /// <param name="statistics">The usage statistics</param>
        public ModelUsageStatisticsResponse(string interval = default(string), System.Collections.Generic.IList<UsageStatistics> statistics = default(System.Collections.Generic.IList<UsageStatistics>))
        {
            Interval = interval;
            Statistics = statistics;
        }

        /// <summary>
        /// Gets or sets the input interval for this response
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "interval")]
        public string Interval { get; set; }

        /// <summary>
        /// Gets or sets the usage statistics
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "statistics")]
        public System.Collections.Generic.IList<UsageStatistics> Statistics { get; set; }

    }
}
