// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace BuildIt.CognitiveServices.Models
{
    using System.Linq;

    public partial class RuleParameters
    {
        /// <summary>
        /// Initializes a new instance of the RuleParameters class.
        /// </summary>
        public RuleParameters() { }

        /// <summary>
        /// Initializes a new instance of the RuleParameters class.
        /// </summary>
        public RuleParameters(BlockListParameters blockList = default(BlockListParameters), WhiteListParameters whiteList = default(WhiteListParameters), UpsaleParameters upsale = default(UpsaleParameters), PerSeedBlockListParameters perSeedBlockList = default(PerSeedBlockListParameters), FeatureBlockListParameters featureBlockList = default(FeatureBlockListParameters), FeatureWhiteListParameters featureWhiteList = default(FeatureWhiteListParameters))
        {
            BlockList = blockList;
            WhiteList = whiteList;
            Upsale = upsale;
            PerSeedBlockList = perSeedBlockList;
            FeatureBlockList = featureBlockList;
            FeatureWhiteList = featureWhiteList;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "blockList")]
        public BlockListParameters BlockList { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "whiteList")]
        public WhiteListParameters WhiteList { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "upsale")]
        public UpsaleParameters Upsale { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "perSeedBlockList")]
        public PerSeedBlockListParameters PerSeedBlockList { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "featureBlockList")]
        public FeatureBlockListParameters FeatureBlockList { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "featureWhiteList")]
        public FeatureWhiteListParameters FeatureWhiteList { get; set; }

    }
}
