// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace BuildIt.CognitiveServices.Models
{
    using System.Linq;

    public partial class RuleRequestInfo
    {
        /// <summary>
        /// Initializes a new instance of the RuleRequestInfo class.
        /// </summary>
        public RuleRequestInfo() { }

        /// <summary>
        /// Initializes a new instance of the RuleRequestInfo class.
        /// </summary>
        /// <param name="type">Type of rule</param>
        /// <param name="parameters">Parameters for rule</param>
        public RuleRequestInfo(string type = default(string), RuleParameters parameters = default(RuleParameters))
        {
            Type = type;
            Parameters = parameters;
        }

        /// <summary>
        /// Gets or sets type of rule
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// Gets or sets parameters for rule
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "parameters")]
        public RuleParameters Parameters { get; set; }

    }
}
