// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace BuildIt.CognitiveServices.Models
{
    using System.Linq;

    public partial class TopicDetectionInputV2
    {
        /// <summary>
        /// Initializes a new instance of the TopicDetectionInputV2 class.
        /// </summary>
        public TopicDetectionInputV2() { }

        /// <summary>
        /// Initializes a new instance of the TopicDetectionInputV2 class.
        /// </summary>
        /// <param name="stopWords">List of words to ignore from all documents
        /// during pre-processing.</param>
        /// <param name="topicsToExclude">List of topics to omit from the
        /// response.</param>
        public TopicDetectionInputV2(System.Collections.Generic.IList<string> stopWords = default(System.Collections.Generic.IList<string>), System.Collections.Generic.IList<string> topicsToExclude = default(System.Collections.Generic.IList<string>), System.Collections.Generic.IList<InputV2> documents = default(System.Collections.Generic.IList<InputV2>))
        {
            StopWords = stopWords;
            TopicsToExclude = topicsToExclude;
            Documents = documents;
        }

        /// <summary>
        /// Gets or sets list of words to ignore from all documents during
        /// pre-processing.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "stopWords")]
        public System.Collections.Generic.IList<string> StopWords { get; set; }

        /// <summary>
        /// Gets or sets list of topics to omit from the response.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "topicsToExclude")]
        public System.Collections.Generic.IList<string> TopicsToExclude { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "documents")]
        public System.Collections.Generic.IList<InputV2> Documents { get; set; }

    }
}
