// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace BuildIt.CognitiveServices.Models
{
    using System.Linq;

    public partial class TopicInfoRecordV2
    {
        /// <summary>
        /// Initializes a new instance of the TopicInfoRecordV2 class.
        /// </summary>
        public TopicInfoRecordV2() { }

        /// <summary>
        /// Initializes a new instance of the TopicInfoRecordV2 class.
        /// </summary>
        /// <param name="id">A unique identifier for each topic.</param>
        /// <param name="score">Count of documents assigned to topic.</param>
        /// <param name="keyPhrase">A summarizing word or phrase for the
        /// topic.</param>
        public TopicInfoRecordV2(string id = default(string), double? score = default(double?), string keyPhrase = default(string))
        {
            Id = id;
            Score = score;
            KeyPhrase = keyPhrase;
        }

        /// <summary>
        /// Gets or sets a unique identifier for each topic.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets count of documents assigned to topic.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "score")]
        public double? Score { get; set; }

        /// <summary>
        /// Gets or sets a summarizing word or phrase for the topic.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "keyPhrase")]
        public string KeyPhrase { get; set; }

    }
}
