// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace BuildIt.CognitiveServices.Models
{
    using System.Linq;

    public partial class UpdateModelRequestInfo
    {
        /// <summary>
        /// Initializes a new instance of the UpdateModelRequestInfo class.
        /// </summary>
        public UpdateModelRequestInfo() { }

        /// <summary>
        /// Initializes a new instance of the UpdateModelRequestInfo class.
        /// </summary>
        /// <param name="description">Model description</param>
        /// <param name="activeBuildId">Model active build ID</param>
        public UpdateModelRequestInfo(string description = default(string), long? activeBuildId = default(long?))
        {
            Description = description;
            ActiveBuildId = activeBuildId;
        }

        /// <summary>
        /// Gets or sets model description
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// Gets or sets model active build ID
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "activeBuildId")]
        public long? ActiveBuildId { get; set; }

    }
}
